quiz/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'quiz.views.home', name='home'),
    # url(r'^quiz/', include('quiz.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^quizzes/', include('quizzes.urls', namespace='quizzes')),
)

quizzes/urls.py
from django.conf.urls import patterns, url
from quizzes import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^(?P<exam_id>\d+)/$', views.examination, name='examination'),
	url(r'^(?P<exam_id>\d+)/answer/$', views.answer, name='answer'),
	url(r'^(?P<exam_id>\d+)/result/$', views.result, name='result'),
)

quizzes/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

class Exam(models.Model):
    deadline= models.DateField('Examination Deadline')
    description= models.CharField(max_length=180)
    score= models.DecimalField(max_digits=5, decimal_places=2, default=0.00)

    def __str__(self):
        return 'Exam number {0}'.format(self.id)

    def valid_date(self):
        now = datetime.date.today()
        return self.deadline >  now

class Question(models.Model):
    exam= models.ForeignKey(Exam)
    text= models.CharField(max_length=200)

    def __str__(self):
        return self.text

class Options(models.Model):
    question= models.ForeignKey(Question)
    text= models.CharField(max_length=200)
    value = models.BooleanField()
    chosen = models.BooleanField()

    def __str__(self):
        return self.text

quizzes/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from quizzes.models import Exam, Question, Options

def index(request):
    exam_list = Exam.objects.order_by('deadline')[:5]
    context = {'exam_list': exam_list}
    return render(request, 'quizzes/index.html', context)

def examination(request, exam_id):
    exam = get_object_or_404(Exam, pk=exam_id)
    return render(request, 'quizzes/examination.html', {'exam': exam})

def result(request, exam_id):
    exam = get_object_or_404(Exam, pk=exam_id)
    return render(request, 'quizzes/result.html', {'exam': exam})

def answer(request, exam_id):
    p = get_object_or_404(Exam, pk=exam_id)
    try:
        selected_choice = p.question_set.get(pk=request.POST['choice'])
    except (KeyError, Options.DoesNotExist):
        # Redisplay the poll voting form.
        return render(request, 'quizzes/examination.html', {
            'exam': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        # selected_choice.votes += 1
        # selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

quiz/templates/quiz/base_site.html
{% extends "admin/base.html" %}
{% load i18n %}

{% block title %}{{ title }} | {% trans 'Django site admin' %}{% endblock %}

{% block branding %}
<h1 id="site-name">Quizzer Administration</h1>
{% endblock %}

{% block nav-global %}{% endblock %}

quiz/templates/quiz/index.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/dashboard.css" %}" />{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
<div id="content-main">

{% if app_list %}
    {% for app in app_list %}
        <div class="module">
        <table>
        <caption>
            <a href="{{ app.app_url }}" class="section" title="{% blocktrans with name=app.name %}Models in the {{ name }} application{% endblocktrans %}">
                {% blocktrans with name=app.name %}{{ name }}{% endblocktrans %}
            </a>
        </caption>
        {% for model in app.models %}
            <tr>
            {% if model.admin_url %}
                <th scope="row"><a href="{{ model.admin_url }}">{{ model.name }}</a></th>
            {% else %}
                <th scope="row">{{ model.name }}</th>
            {% endif %}

            {% if model.add_url %}
                <td><a href="{{ model.add_url }}" class="addlink">{% trans 'Add' %}</a></td>
            {% else %}
                <td>&nbsp;</td>
            {% endif %}

            {% if model.admin_url %}
                <td><a href="{{ model.admin_url }}" class="changelink">{% trans 'Change' %}</a></td>
            {% else %}
                <td>&nbsp;</td>
            {% endif %}
            </tr>
        {% endfor %}
        </table>
        </div>
    {% endfor %}
{% else %}
    <p>{% trans "You don't have permission to edit anything." %}</p>
{% endif %}
</div>
{% endblock %}

{% block sidebar %}
<div id="content-related">
    <div class="module" id="recent-actions-module">
        <h2>{% trans 'Recent Actions' %}</h2>
        <h3>{% trans 'My Actions' %}</h3>
            {% load log %}
            {% get_admin_log 10 as admin_log for_user user %}
            {% if not admin_log %}
            <p>{% trans 'None available' %}</p>
            {% else %}
            <ul class="actionlist">
            {% for entry in admin_log %}
            <li class="{% if entry.is_addition %}addlink{% endif %}{% if entry.is_change %}changelink{% endif %}{% if entry.is_deletion %}deletelink{% endif %}">
                {% if entry.is_deletion or not entry.get_admin_url %}
                    {{ entry.object_repr }}
                {% else %}
                    <a href="{{ entry.get_admin_url }}">{{ entry.object_repr }}</a>
                {% endif %}
                <br/>
                {% if entry.content_type %}
                    <span class="mini quiet">{% filter capfirst %}{% trans entry.content_type.name %}{% endfilter %}</span>
                {% else %}
                    <span class="mini quiet">{% trans 'Unknown content' %}</span>
                {% endif %}
            </li>
            {% endfor %}
            </ul>
            {% endif %}
    </div>
</div>
{% endblock %}

quizzes/templates/quizzes/examination.html
<title>{{ exam }}</title>
<h2> {{ exam.description }}... </h2>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'quizzes:answer' exam.id %}" method="post">
{% csrf_token %}
{% for question in exam.question_set.all %}
  <li> {{ question.text }} </li>
  <ul>
  {% for option in question.options_set.all %}
    <input type="radio" name="choice" id="options{{ forloop.counter }}" value="{{ options.id }}" />
    <label for="options{{ forloop.counter }}">{{ option.text }} </label></br>
  {% endfor %}
  </ul>
  </br>
{% endfor %}
<input type="submit" value="Submit answers" />
</form> <br>
<a href="{% url 'quizzes:index' %}"> BACK </a>

quizzes/templates/quizzes/index.html
<title> Exam List | </title>
<h1> Exam List </h1>
{% if exam_list %}
    <ul>
    {% for exam in exam_list %}
        <li>{{ exam }} --- <a href="{% url 'quizzes:examination' exam.id %}">{{ exam.description }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No exams are available.</p>
{% endif %}

quizzes/templates/quizzes/result.html
<title> Results | {{exam}} </title>
Result of {{ exam }}